---
title: DADA
timezone: Europe/Helsinki
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-cayman
title: DADA ry
description: New Media Student organization
google_analytics: UA-77263046-2
